# Uncomment the next line to define a global platform for your project
 platform :ios, '12.0'
source 'https://github.com/aliyun/aliyun-specs.git'
source 'https://github.com/CocoaPods/Specs.git'
post_install do |installer|
      installer.pods_project.targets.each do |target|
          target.build_configurations.each do |config|
          config.build_settings['ENABLE_BITCODE'] = 'NO'
          config.build_settings['CODE_SIGN_IDENTITY'] = ''
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
          xcconfig_path = config.base_configuration_reference.real_path
          xcconfig = File.read(xcconfig_path)
          xcconfig_mod = xcconfig.gsub(/DT_TOOLCHAIN_DIR/, "TOOLCHAIN_DIR")
          File.open(xcconfig_path, "w") { |file| file << xcconfig_mod }
        end
    end
end
target 'MeariSDKDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  
  use_frameworks!

  # Pods for MeariSDKDemo
#  pod 'Braintree/PayPal'
  pod 'AFNetworking', '4.0.1'
  pod 'MJExtension',  '~>3.0.17'
  pod 'AliyunOSSiOS', '~>2.10.7'
  pod 'AWSS3'

end
