# Uncomment the next line to define a global platform for your project
 platform :ios, '12.0'
#source 'https://github.com/aliyun/aliyun-specs.git'
#source 'https://github.com/CocoaPods/Specs.git'

target 'MeariSDKDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MeariSDKDemo
#  pod 'Braintree', '~> 5.24.1'
  pod 'AFNetworking', '4.0.1'
  pod 'MJExtension', '~> 3.4.1'
  pod 'AliyunOSSiOS', '~> 2.10.18'
  pod 'AWSS3'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      #Fix error: User SDK does not contain 'libarclite' at the path..
      config.build_settings["IPHONEOS_DEPLOYMENT_TARGET"] = "12.0"
    end
  end
end
